### PR TITLE
feat: support `script:src` attributes

### LINKED ISSUE #196: How to get html-loader to process HTML's script's src?
**I'm submitting a bug report**
Question was asked [here](https://stackoverflow.com/questions/54594114/how-to-get-html-loader-to-process-htmls-scripts-src)

**Webpack version:**
4.28.2

**HTML-Loader version:**
0.5.5

**Please tell us about your environment:**
OSX 10.14.2

**Current behavior:**
script's `src` attribute outputs `[object Object]`

**Expected/desired behavior:**
script's `src` attribute outputs `/path/to/bundle.js`

* **How to reproduce** 
Fork [this](https://github.com/dreadcast/html-loader) to reproduce.

* **Browser:** all

* **Language:** Javascript

### PR DESCRIPTION
**Pull request by evilebottnawi**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [x] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case

Support `<script src="./source.js">`

### Breaking Changes

Yes

### Additional Info

fixes #196

### CODE REVIEW

**Comment by dipeshba** [comment]
Hi, is this working in latest version? I am using v1.1.0 but this is still not working?

**Comment by evilebottnawi** [comment]
Working

**Comment by dipeshba** [comment]
This is my current webpack config:

`const path = require('path');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');

module.exports = {
    entry: [
        require.resolve("./src/html/pages/index.html"),
    ],
    mode: "development",
    plugins: [
        new CleanWebpackPlugin(),
    ],
    module: {
        rules: [
            {
                test: /\.(css|pcss|postcss)$/i,
                use: [
                    {
                        loader: 'file-loader',
                        options: {
                            name: '[name].[ext]',
                        }
                    },
                    { loader: 'extract-loader' },
                    { loader: 'css-loader', options: {} },
                    { loader: 'postcss-loader', options: {} }
                ],
            },
            {

                test: /\.html$/i,
                use: [
                    {
                        loader: 'file-loader',
                        options: {
                            name: '[name].[ext]',
                        }
                    },
                    { loader: 'extract-loader' },
                    {
                        loader: 'html-loader',
                        options: { },
                    },
                    {
                        loader: path.resolve(__dirname, 'loaders/nunjucks-loader.js'),
                    }
                ]
            },

            {
                test: /\.(gif|png|jpe?g|svg)$/i,
                use: [

                    {
                        loader: 'file-loader',
                        options: {
                            name: '[name].[ext]',
                        }
                    },
                    {
                        loader: 'image-webpack-loader'
                    }
                ]
            },
        ]
    }
};
`
But after my html page in source directory is processed and added to 'dist' directory, I still get:
`<script src="[object Object]"></script>`

**Comment by evilebottnawi** [comment]
@dipeshba Please do not put configuration in an issue, just create simple reproducible test repo

**Comment by dipeshba** [comment]
Here is the link to repository. You can use `yarn build`, or `npx webpack `  to build `dist` folder. 
https://github.com/dipeshba/html-loader-issue

**Comment by evilebottnawi** [comment]
@dipeshba Please put it in the issue

**Comment by dipeshba** [comment]
I have updated readme file in the repo. Not beautifully formatted. But I hope it explains the issue.

**Pull request merged**
