### PR TITLE
solution for isuue #330

### PR DESCRIPTION
**Pull request by RebelClone**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

  Issue #330 https://github.com/webpack-contrib/html-loader/issues/330
The url of sprite svg was getting trunctared if the relative path from the sprite file left hand side was shorter comapred to right hand side

### Additional Info
how to sign Contributor License Agreement (CLA)

### CODE REVIEW

**Review by alexander-akait — CHANGES_REQUESTED** [review]
Please add tests

**Comment by RebelClone** [comment]
sry but i m new to js i dont know how to add test

**Comment by alexander-akait** [comment]
- Add HTML example here https://github.com/webpack-contrib/html-loader/blob/master/test/fixtures/sources.html
- Change source to exiting image
- Run `npm run test:only -- -u`

**Comment by RebelClone** [comment]
is this breaking something

**Pull request closed without merging**
