### PR TITLE
fix: merge attributes without tag and attributes with tag

### LINKED ISSUE #405: When extending default sources, tag is not optional
(I wasn't sure if this should be a bug report or a documentation issue.  I guess it depends on whether the outcome ends up being a fix to the docs, or a fix to the code)

### Bug report

According to the documentation for `options.sources.list`:

> Using `"..."` syntax allows you to extend default supported tags and attributes

and...

> If the tag name is not specified it will process all the tags.

### Actual Behavior

When extending the default sources (`"..."`), omitting `tag` from any overrides does not work:

```js
// This does not work
options: {
	sources: {
		list: [
			"...",
			{ attribute: "my-custom-src", type: "src" }
		]
	}
}
```

```js
// ...but this does work
options: {
	sources: {
		list: [
			"...",
			{ tag: "img", attribute: "my-custom-src", type: "src" }
		]
	}
}
```

### Expected Behavior

It should be possible to omit `tag`, as per the documentation.

There are no existing tests that cover this exact scenario.

### How Do We Reproduce?

A full repro can be found here:
https://github.com/scottohara/webpack-html-loader-custom-source

```
  System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 138.19 MB / 16.00 GB
  Binaries:
    Node: 16.9.1 - ~/.asdf/installs/nodejs/16.9.1/bin/node
    npm: 7.23.0 - ~/.asdf/installs/nodejs/16.9.1/.npm/bin/npm
  Browsers:
    Chrome: 94.0.4606.81
    Chrome Canary: 97.0.4668.2
    Firefox: 84.0.1
    Safari: 15.0
  Packages:
    html-loader: 2.1.2 => 2.1.2 
    webpack: 5.58.2 => 5.58.2 
    webpack-cli: 4.9.0 => 4.9.0 
```

### PR DESCRIPTION
**Pull request by scottohara**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Fixes #405 

When processing attributes, merge attributes for any tag with attributes for the specific tag:

```js
const handlers = new Map([
  ...(options.sources.list.get("*") || new Map()),
  ...(options.sources.list.get(tagName.toLowerCase()) || new Map()),
]);
```

(More info: https://github.com/webpack-contrib/html-loader/pull/408#issuecomment-955156062)

### Breaking Changes

None

### CODE REVIEW

**Comment by scottohara** [comment]
OK, so if we're considering the current behaviour as a bug, then perhaps what I would suggest is a change to how the `sources-plugin.js` determines the handlers for the current tag being processed.

Given a config like this:

```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.html$/i,
        loader: "html-loader",
        options: {
          sources: {
            list: [
              // All default supported tags and attributes
              "...",
              {
                attribute: "data-src",
                type: "src",
              },
            ],
          },
        },
      },
    ],
  },
};
```

...internally, the `normalizeSourcesList()` function produces a Map like this:

```js
const result = new Map([
 ...
 ["img", new Map([
   ["src", { type: srcType }],
   ["srcset", { type: srcsetType }]
 )],
 ...
 ["*", new Map([
   ["data-src", { type: srcType }]
 ])
]);
```

### Current behaviour

When processing a tag, the handlers are determined as:

```js
const handlers =
  options.sources.list.get(tagName.toLowerCase()) ||
  options.sources.list.get("*");
```

...which means that for an `` tag, only the defaults are used:

```sh
Map(2) {'src' => {…}, 'srcset' => {…}}
```

### Proposed change

The proposal is to use a union of the map entries:

```js

const handlers = new Map([
  ...options.sources.list.get(tagName.toLowerCase() ?? new Map(),
  ...options.sources.list.get("*") ?? new Map()
]);
```

The result is a merged map of both the attributes specific to the tag, and any attributes that apply to all tags:

```sh
Map(3) {'src' => {…}, 'srcset' => {…}, 'data-src' => {…}}
```

(The `?? new Map()` guards against either of those being undefined.)

If that solution sounds OK to you, I am happy to modify this PR accordingly.

**Comment by alexander-akait** [comment]
Yes, let's do it

**Review by alexander-akait — COMMENTED** [review]
And let's add test case

**Comment by alexander-akait** [comment]
Big thanks for the PR, fixed here https://github.com/webpack-contrib/html-loader/pull/410, `Map` needs to be checked on `size`, we need do release due some regressions in previous version, so I go ahead and do it, anyway, thanks again, release will be today

**Pull request closed without merging**
