### PR TITLE
build: drop node v12

### PR DESCRIPTION
**Pull request by snitin315**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### CODE REVIEW

**Comment by alexander-akait** [comment]
@snitin315 Sorry for delay, I will return to this after drop Node.js supporting in CSS loaders/plugins

**Comment by snitin315** [comment]
@alexander-akait No worries, take your time.

**Review by alexander-akait — APPROVED** [review]

**Comment by alexander-akait** [comment]
Done here https://github.com/webpack-contrib/html-loader/pull/443, sorry for delay :disappointed:

**Pull request closed without merging**
