### PR TITLE
Optimize the img tag SRC attribute is empty

### PR DESCRIPTION
**Pull request by gongdf**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

when html file have
```html
<img src="" />
```
tag, We should return 
```html
 <img src="" />
```
instead of 
```html
<img src="xxxHTMLLINKxxx0.241767597227476870.4882104576985471xxx" />
```

### CODE REVIEW

**Comment by gongdf** [comment]
> Please add tests and accept CLA

ok，already added

**Comment by evilebottnawi** [comment]
@gongdf please fix conflicts

**Comment by gongdf** [comment]
> @gongdf please fix conflicts

Do you need to merge the latest master code?I modified it based on tag v0.5.5, and I hope the code modified is version v0.5.5, we used version v0.5.5, I didn't quite understand it when I used it for the first time , sorry! What do I need to do?

**Comment by evilebottnawi** [comment]
@gongdf update your `html-loader` to latest version, bug doesn't exists in the latest version

**Comment by gongdf** [comment]
> @gongdf update your `html-loader` to latest version, bug doesn't exists in the latest version

ok! I'll have a try

**Comment by EnjoyChan** [comment]
image
use version 1.1.0， when use empty src, it throws an error. can it just been igored, input src="" and  output src=""

**Pull request closed without merging**
