### PR TITLE
Fix: backticks in templates cause errors if `interpolate` flag is set

### PR DESCRIPTION
**Pull request by rluba**
**Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
Backticks in templates cause an exception if the `interpolate` flag is set.

**What is the new behavior?**
It works :-)

**Does this PR introduce a breaking change?**
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by rluba** [comment]
Any progress on this? Seems like the checks have stalled for some reason.

**Comment by rluba** [comment]
@evilebottnawi Friendly ping?

**Comment by rluba** [comment]
@evilebottnawi @hemanth @d3viant0ne Is there anything that prevents this PR from being merged? It’s now more than 4 months old.

**Comment by rluba** [comment]
@evilebottnawi Hi. It’s been a while. Any reason why this can’t be merged?

**Comment by evilebottnawi** [comment]
Sorry, but the `interpolate` option was removed without replacement, please consider on migration template system and relevant loader, I will provide simple templating without extra logic in examples in near future

**Comment by evilebottnawi** [comment]
Anyway thanks for the PR

**Pull request closed without merging**
