### PR TITLE
refactor(loader): v1.0.0

### PR DESCRIPTION
**Pull request by michael-ciniawsky**
#### `url` (`options.url`)

**file.html**
```html
<body>
 <img src="path/to/file.png">
</body>
```
**module.js**
```js
import HTML__URL__0 from 'path/to/file.png';

export default `<body>
  <img src="${HTML__URL__0}">
</body>
`
```

#### `import` (`options.import`)

**file.html**
```html
<body>
  <import src="path/to/import.html">
</body>
```
**module.js**
```js
import HTML__IMPORT__0 from 'path/to/import.html';

export default `<body>
  ${HTML__IMPORT__0}
</body>
`
```

#### `template` (`options.template`)

**file.html**
```html
<body>
  <h1>${ _.hello }</h1>
</body>
```

**entry.js**
```js
import template from './file.html';

const html = template({ hello: 'Hello World' });

document.body.innerHTML = `${html}`;
```

### `minimize` (`options.minimize`)

- Using [htmlnano](https://github.com/posthtml/htmlnano)

#### `root` (`options.root`)

- Removed

#### `attrs` (`options.attrs`) 

- Removed (will be handled by the `url` plugin)

#### `interpolate` (`options.interpolate`)

- Removed in favor of `options.template`

#### `exportAsDefault && exportAsEs6Default` (`options.exportAsDefault|options.exportAsEs6Default`)

- Removed in favor of just exporting an ES2015 Module :)

### `Issues`

- closes all Issues prior to `html-loader <= v1.0.0`

### `TODO`

- port changes from `src/lib/plugins/url` to `posthtml-include` (PR #?, Issue #158, Issue #159)
   - add plugin option to filter urls `{Regex|Function}`
- port changes from `src/lib/plugins/import` to `posthtml-url` (PR #?, Issue #158)
   - add plugin option to filter urls `{Regex|Function}`

### `Status`

|Name|Status|
|:-----:|:-----:|
|Default| ✅ |
|HTML URLs|✅|
|HMTL Imports| ✅|
|HMTL Templates| ✅|
|HTML Minification| ✅ |

### `Blocked by`

- ~~[`posthtml/posthtml` #236](https://github.com/posthtml/posthtml/pull/236)~~ **(Merged && Released  🎉)**

### CODE REVIEW

**Comment by d3viant0ne** [comment]
@michael-ciniawsky - Don't worry about splitting things in this PR. 

Just edit the initial comment in #155 and add the appropriate `Breaking Changes` & we can handle the release notes portion there.

**Comment by michael-ciniawsky** [comment]
I rebase the commit into `CHANGELOG` suiteable commits, revisit this one more time and land it on `next` during the day ? So folks can test it out and I add the `filters` for `options.url` && `options.import` in follow up PR's ? Especially the current default `url` filter is a bit too  aggressive :D

@d3viant0ne What is required to enable to CI e.g ok/sufficient to change the `travis.yml`  to remove the `master only` stuff there (making a note to add it back, once this may land on `master` of course 🙃)? Or how should we proceed at best ?

**Comment by d3viant0ne** [comment]
https://github.com/webpack-contrib/html-loader/blob/acda6f9026df5d9b341728cd543b5ed43cacfc4e/.travis.yml#L6

Just need to add `- next` to the `branches list`

**Comment by d3viant0ne** [comment]
@michael-ciniawsky - We can land it now if you want. Once we are reasonably sure about `next` after this lands, we can throw out an initial `.alpha-0` build to get people beating on it.

**Comment by michael-ciniawsky** [comment]
I have one cricital bug fix locally and `e2e` tests (JSDOM), just a few minutes (~30) 😛  for final self review and to split the commits.

**Comment by d3viant0ne** [comment]
@michael-ciniawsky - When you are satisfied with this, just merge it into `next`. I'll apply defaults 2.0 to that branch once it's finished & we can start getting alpha builds out.

**Comment by michael-ciniawsky** [comment]
@d3viant0ne I just saw your [comment](https://github.com/webpack-contrib/html-loader/pull/157#issuecomment-351836029) I can leave the `defaults v1.6.0...2.0.0` out of this PR if you want I test it out for myself in e.g `style-loader, css-loader` instead. Should I leave it here ?

**Comment by michael-ciniawsky** [comment]
kk I will leave it and open an issue alongside with the others I open for other contribs and as remaining TODO list, finally spit the commit here, land this PR in the next few moments (one final CI run) and then on to the CSS related stuff... 😛

**Comment by michael-ciniawsky** [comment]
CircleCI is expected to fail for this PR (`webpack-defaults@next`) 

The `webpack` Canary failure of the `e2e` tests is related to [`file-loader` #234](https://github.com/webpack-contrib/file-loader/pull/234)

**Pull request merged**
