### PR TITLE
Support more attributes by default

### PR DESCRIPTION
**Pull request by EslamHiko**
This PR contains a:

- [ ] **bugfix**
- [x] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case
solve : https://github.com/webpack-contrib/html-loader/issues/259

### Breaking Changes
No

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@EslamHiko unfortunately it potential breaking change, we should wait a bit before the release of the new major version

**Comment by Austaras** [comment]
When will 2.0 be released? Is there a ETA or something

**Comment by evilebottnawi** [comment]
@Austaras Why do you need `2.0`?

**Comment by Austaras** [comment]
Because I want to use this pr and related issue seems to be labeled as 2.0

**Pull request closed without merging**
