### PR TITLE
fix: typo

### PR DESCRIPTION
**Pull request by Scrum**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [x] **typo fix**
- [ ] **metadata update**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Sorry, I would not be attentive initially

**Comment by Scrum** [comment]
@evilebottnawi do not worry, I thought it was just a mistake, maybe you should make a footnote about it

**Comment by evilebottnawi** [comment]
Yes, we should improve docs about it, we do some refactor in loader methods for webpack@5, so we will do it after stable release

**Comment by Scrum** [comment]
#252

**Pull request closed without merging**
